const assert = require('assert');
const fs = require('fs');
const html = fs.readFileSync('index.html','utf8');
const script = fs.readFileSync('script.js','utf8');
assert(html.includes('<script src="data/countries.js"></script>'));
assert(html.includes('<script src="flag-game.js"></script>'));
assert(!html.includes('const countries=['), 'country master must not be duplicated');
assert(script.includes("state.ui!=='ready'"), 'choices are disabled outside player input');
assert(script.includes('コンピュータが考えています…'));
assert(script.includes("state.hint>=3?0:state.hint+1"), 'hints must advance in stages');
assert(script.includes("short:2000, normal:4000, long:7000, manual:null"), 'four learning durations must be available');
assert(script.includes('clearTimer()'), 'async transitions must be cancellable');
console.log('flag-shiritori tests passed');
