const assert = require('assert');
const { createLocalPlayers, activePlayers, findNextActivePlayer, eliminatePlayer, buildRankings } = require('../core.js');
let players = createLocalPlayers(2);
let order = [];
eliminatePlayer(players, 0, 'timeout', order);
assert.strictEqual(activePlayers(players).length, 1);
assert.strictEqual(buildRankings(players, order)[0].id, 'player-2');
players = createLocalPlayers(3); order = [];
eliminatePlayer(players, 1, 'invalid-word', order);
assert.strictEqual(findNextActivePlayer(0, players).index, 2);
assert.strictEqual(findNextActivePlayer(2, players).index, 0);
players = createLocalPlayers(4); order = [];
eliminatePlayer(players, 2, 'invalid-word', order);
eliminatePlayer(players, 0, 'wrong-start', order);
eliminatePlayer(players, 3, 'give-up', order);
const ranks = buildRankings(players, order);
assert.deepStrictEqual(ranks.map(r => r.id), ['player-2', 'player-4', 'player-1', 'player-3']);
assert.strictEqual(ranks[0].displayReason, '最後まで残りました');
assert.strictEqual(players[0].eliminationReason, 'wrong-start');
players = createLocalPlayers(4); order = [];
eliminatePlayer(players, 3, 'timeout', order);
assert.strictEqual(findNextActivePlayer(2, players).index, 0);
eliminatePlayer(players, 0, 'timeout', order);
assert.notStrictEqual(findNextActivePlayer(2, players).index, 0);
eliminatePlayer(players, 1, 'invalid-word', order);
assert.strictEqual(findNextActivePlayer(2, players).isGameOver, true);
const before = order.length;
eliminatePlayer(players, 1, 'invalid-word', order);
assert.strictEqual(order.length, before);
players = createLocalPlayers(3);
assert.strictEqual(activePlayers(players).length, 3);
console.log('multiplayer tests passed');
