const assert = require('assert');
global.window = global; global.MANABI_DATA = {};
delete require.cache[require.resolve('../data/prefectures.js')];
delete require.cache[require.resolve('../data/animals.js')];
delete require.cache[require.resolve('../data/countries.js')];
delete require.cache[require.resolve('../data/foods.js')];
require('../data/countries.js');
require('../data/prefectures.js');
require('../data/animals.js');
require('../data/foods.js');
const { THEME_DEFINITIONS, getThemeWords, getThemeStats, validateThemeData, validatePrefectureData } = require('../core.js');
assert.deepStrictEqual(Object.keys(THEME_DEFINITIONS), ['prefectures', 'countries', 'animals', 'foods', 'mix']);
assert.strictEqual(getThemeWords(global.MANABI_DATA, 'prefectures').length, 47);
assert.deepStrictEqual(getThemeWords(global.MANABI_DATA, 'animals'), []);
assert.deepStrictEqual(getThemeWords(global.MANABI_DATA, 'missing'), []);
assert.strictEqual(getThemeStats(global.MANABI_DATA, 'prefectures').isPlayable, true);
assert.strictEqual(getThemeStats(global.MANABI_DATA, 'countries').isPlayable, true);
assert.strictEqual(validatePrefectureData(getThemeWords(global.MANABI_DATA, 'prefectures')).count, 47);
assert.strictEqual(validateThemeData(getThemeWords(global.MANABI_DATA, 'foods')).count, 0);
console.log('theme tests passed');
