const assert = require('assert');
global.window = global; global.MANABI_DATA = {};
delete require.cache[require.resolve('../data/prefectures.js')];
require('../data/prefectures.js');
const { WordValidator, DEFAULT_SETTINGS, validatePrefectureData } = require('../core.js');
const words = global.MANABI_DATA.prefectures;
const settings = { ...DEFAULT_SETTINGS, stripPrefectureSuffix: true };
const validator = new WordValidator(words, settings);
const empty = { usedIds: new Set(), requiredChar: '' };
assert.strictEqual(words.length, 47);
const problems = validatePrefectureData(words);
assert.deepStrictEqual(problems.duplicateIds, []);
assert.deepStrictEqual(problems.duplicateNames, []);
assert.deepStrictEqual(problems.emptyReadings, []);
assert.deepStrictEqual(problems.missingFields, []);
assert.deepStrictEqual(problems.invalidDifficulty, []);
assert.strictEqual(validator.findWord('東京都').id, 'tokyo');
assert.strictEqual(validator.findWord('東京').id, 'tokyo');
assert.strictEqual(validator.findWord('  トウキョウト  ').id, 'tokyo');
assert.strictEqual(validator.validate('京都', { usedIds: new Set(), requiredChar: 'き' }).ok, true);
assert.strictEqual(validator.validate('京都', { usedIds: new Set(), requiredChar: 'と' }).ok, false);
assert.strictEqual(validator.validate('横浜市', empty).reason, 'このゲームの言葉リストには登録されていません。');
assert.strictEqual(validator.validate('', empty).reason, '答えを入力してください。');
const used = { usedIds: new Set(['tokyo']), requiredChar: '' };
assert.strictEqual(validator.validate('東京', used).ok, false);
assert.strictEqual(validator.validate('東京都', used).ok, false);
assert.strictEqual(validator.validate('とうきょうと', used).ok, false);
console.log('word-validator tests passed');
