const assert = require('assert');
const { WordNormalizer, WordValidator, DEFAULT_SETTINGS } = require('../core.js');
const soft = { ...DEFAULT_SETTINGS, stripPrefectureSuffix: true };
const strict = { ...DEFAULT_SETTINGS, stripPrefectureSuffix: false };
assert.strictEqual(WordNormalizer.katakanaToHiragana('トウキョウト'), 'とうきょうと');
assert.strictEqual(WordNormalizer.normalizeForLookup('  東　京  '), '東京');
assert.strictEqual(WordNormalizer.normalizeForLookup('きょうと'), 'きょうと');
assert.strictEqual(WordNormalizer.normalizeForLookup('キョウト'), 'きょうと');
assert.strictEqual(WordNormalizer.normalizeForLookup('ｷｮｳﾄ'), 'きょうと');
assert.notStrictEqual(WordNormalizer.normalizeForLookup('きようと'), WordNormalizer.normalizeForLookup('きょうと'));
assert.strictEqual(WordNormalizer.normalizeForLooseComparison('きようと', { normalizeSmallKana: true }), WordNormalizer.normalizeForLooseComparison('きょうと', { normalizeSmallKana: true }));
assert.strictEqual(WordNormalizer.firstChar('とうきょうと', soft), 'と');
assert.strictEqual(WordNormalizer.lastChar('とうきょうと', soft), 'う');
assert.strictEqual(WordNormalizer.lastChar('とうきょうと', strict), 'と');
assert.strictEqual(WordNormalizer.endsWithN('にほん', soft), true);
global.window = global; global.MANABI_DATA = {};
delete require.cache[require.resolve('../data/prefectures.js')];
require('../data/prefectures.js');
assert.strictEqual(global.MANABI_DATA.prefectures.find(w => w.id === 'tokyo').reading, 'とうきょうと');
const strictValidator = new WordValidator([{ id: 'kyoto', name: '京都府', reading: 'きょうとふ', aliases: ['京都', 'きょうと'] }], { ...DEFAULT_SETTINGS, normalizeSmallKana: false });
assert.strictEqual(strictValidator.findWord('きようと'), null);
const looseValidator = new WordValidator([{ id: 'kyoto', name: '京都府', reading: 'きょうとふ', aliases: ['京都', 'きょうと'] }], { ...DEFAULT_SETTINGS, normalizeSmallKana: true });
assert.strictEqual(looseValidator.findWord('きようと').id, 'kyoto');
console.log('word-normalizer tests passed');
